USE krautundrueben;

-- TODO: Lieferant telefon und email?

INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3001, 'Eppendorfer Landstrasse', '104', '20249', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3002, 'Bananen Landstrasse', '15', '20249', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3003, 'Ohmstraße', '23', '22765', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3004, 'Bilser Berg', '6', '20459', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3005, 'Alter Teichweg', '95', '22049', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3006, 'Stübels', '10', '22835', 'Barsbüttel', 'Hamburg', 'DEUTSCHLAND'); -- TODO Stadt
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3007, 'Grotelertwiete', '4a', '21075', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3008, 'Küstersweg', '3', '21079', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3009, 'Neugrabener Bahnhofstraße', '30', '21149', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3010, 'Elbchaussee', '228', '22605', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3011, 'Dorfstraße', '74', '24354', 'Weseby', 'Hamburg', 'DEUTSCHLAND'); -- TODO stadt
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3012, 'Westerjork 74', '76', '21635', 'Jork', 'Hamburg', 'DEUTSCHLAND'); -- TODO stadt
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (3013, 'Molkereiwegkundekunde', '13', '19217', 'Dechow', 'Hamburg', 'DEUTSCHLAND'); -- TODO stadt

INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('wellensteyn', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('foede', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('leberer', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('soerensen', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('schnitter', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('maurer', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('gessert', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('haessig', 'ASJKDASKJD921717AJSKD', 'MOMMY');
INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('urocki', 'ASJKDASKJD921717AJSKD', 'MOMMY');

INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2001, 3001,'Wellensteyn','Kira','1990-05-05','040/443322','k.wellensteyn@yahoo.de', true, 'wellensteyn');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2002,3003, 'Foede','Dorothea','2000-03-24','040/543822','d.foede@web.de', true, 'foede');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2003, 3004, 'Leberer','Sigrid','1989-09-21','0175/1234588','sigrid@leberer.de', false , 'leberer');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2004, 3005, 'Soerensen','Hanna','1974-04-03','040/634578','h.soerensen@yahoo.de', false, 'soerensen');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2005, 3006, 'Schnitter','Marten','1964-04-17','0176/447587','schni_mart@gmail.com', true, 'schnitter');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2006, 3007, 'Maurer','Belinda','1978-09-09','040/332189','belinda1978@yahoo.de', false, 'maurer');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2007, 3008, 'Gessert','Armin','1978-01-29','040/67890','armin@gessert.de', true, 'gessert');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2008, 3009,'Haessig','Jean-Marc','1982-08-30','0178-67013390','jm@haessig.de', true, 'haessig');
INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2009, 3010,'Urocki','Eric','1999-12-04','0152-96701390','urocki@outlook.de', false, 'urocki');


INSERT INTO BESTELLUNG (BESTELLNR, KUNDENNR, BESTELLDATUM) VALUES (1001, 2001, '2025-04-24');

INSERT INTO NAHRUNGSBOX (BOXNR, BEZEICHNUNG, BESCHREIBUNG) VALUES (1, 'vegan', 'Eine Vegane Box mit Veganen sachen!');

INSERT INTO BESTELLUNG_BOX (BESTELLNR, BOXNR, MENGE) VALUES (1001, 1, 1);

INSERT INTO REZEPT (REZEPTNR, NAME, BESCHREIBUNG, VORGEHEN) VALUES (1, 'Lasagne', 'Eine Lasagne', 'mach Lasagne!');

INSERT INTO NAHRUNGSBOX_REZEPT (BOXNR, REZEPTNR, MENGE_REZEPTE) VALUES (1, 1, 1);

INSERT INTO LIEFERANT (LIEFNR, ADRESSNR, NAME) VALUES (101, 3002, 'bananen hof');
INSERT INTO LIEFERANT (LIEFNR, ADRESSNR, NAME) VALUES (102, 3011, 'Bio-Hof Müller'); -- '04354-9080', 'mueller@biohof.de'
INSERT INTO LIEFERANT (LIEFNR, ADRESSNR, NAME) VALUES (103, 3012, 'Obst-Hof Altes Land'); -- '04162-4523', 'info@biohof-altesland.de'
INSERT INTO LIEFERANT (LIEFNR, ADRESSNR, NAME) VALUES (104, 3013, 'Molkerei Henning'); -- '038873-8976', 'info@molkerei-henning.de'

INSERT INTO ZUTAT (ZUTATNR, LIEFNR, BEZEICHNUNG, BESCHREIBUNG, EINHEIT, BESTAND, NETTOPREIS, CO2, KOHLENHYDRATE, PROTEIN, FETT, KALORIEN) VALUES (1, 101, 'Banane', 'Eine gelbe banane', 'einzelne bananae', 5, 1.20, 0.1, 5.8, 2.7, 1.7, 7);

INSERT INTO REZEPT_ZUTAT (REZEPTNR, ZUTATNR, MENGE) VALUES (1, 1, 1);

INSERT INTO ALERGEN (ALERGENNR, BEZEICHNUNG, BESCHREIBUNG) VALUES (1, 'Laktose', 'Keine Milch ertragen');

INSERT INTO ZUTAT_ALERGEN (ZUTATNR, ALERGENNR) VALUES (1, 1);

INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (1, 'vegan', 'Ohne Tierische Produkte', 'ernährungsart', 3);
INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (2, 'vegetarisch', 'Ohne Fleisch Produkte', 'ernährungsart', 2);
INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (3, 'fleisch essend', 'Alle produkte', 'ernährungsart', 1);
-- frutarisch
-- nur fisch und kein fleich

INSERT INTO ZUTAT_ERNAEHRUNGSKATEGORIE (ZUTATNR, ERNAEHRUNGSKATNR) VALUES (1, 1);

