USE krautundrueben;

INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (1, 'Eppendorfer Landstrasse', '104', '20249', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');
INSERT INTO ADRESSE (ADRESSENR, STRASSE, HAURSNR, POSTLEITZAHL, ORT, STADT, LAND) VALUES (2, 'Bananen Landstrasse', '15', '20249', 'Hamburg', 'Hamburg', 'DEUTSCHLAND');

INSERT INTO LOGIN (USERNAME, PASSHASH, SECURITYANSWER) VALUES ('NILS', 'ASJKDASKJD921717AJSKD', 'MOMMY');

INSERT INTO KUNDE (KUNDENNR, ADRESSNR, NACHNAME, VORNAME, GEBURTSDATUM, TELEFON, EMAIL, ABO, USERNAME) VALUES (2001, 1,'Wellensteyn','Kira','1990-05-05','040/443322','k.wellensteyn@yahoo.de', true, 'NILS');

INSERT INTO BESTELLUNG (BESTELLNR, KUNDENNR, BESTELLDATUM) VALUES (1001, 2001, '2025-04-24');

INSERT INTO NAHRUNGSBOX (BOXNR, BEZEICHNUNG, BESCHREIBUNG) VALUES (1, 'vegan', 'Eine Vegane Box mit Veganen sachen!');

INSERT INTO BESTELLUNG_BOX (BESTELLNR, BOXNR, MENGE) VALUES (1001, 1, 1);

INSERT INTO REZEPT (REZEPTNR, NAME, BESCHREIBUNG, VORGEHEN) VALUES (1, 'Lasagne', 'Eine Lasagne', 'mach Lasagne!');

INSERT INTO NAHRUNGSBOX_REZEPT (BOXNR, REZEPTNR, MENGE_REZEPTE) VALUES (1, 1, 1);

INSERT INTO LIEFERANT (LIEFNR, ADRESSNR, NAME) VALUES (1, 2, 'bananen hof');

INSERT INTO ZUTAT (ZUTATNR, LIEFNR, BEZEICHNUNG, BESCHREIBUNG, EINHEIT, BESTAND, NETTOPREIS, CO2, KOHLENHYDRATE, PROTEIN, FETT, KALORIEN) VALUES (1, 1, 'Banane', 'Eine gelbe banane', 'einzelne bananae', 5, 1.20, 0.1, 5.8, 2.7, 1.7, 7);

INSERT INTO REZEPT_ZUTAT (REZEPTNR, ZUTATNR, MENGE) VALUES (1, 1, 1);

INSERT INTO ALERGEN (ALERGENNR, BEZEICHNUNG, BESCHREIBUNG) VALUES (1, 'Laktose', 'Keine Milch ertragen');

INSERT INTO ZUTAT_ALERGEN (ZUTATNR, ALERGENNR) VALUES (1, 1);

INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (1, 'vegan', 'Ohne Tierische Produkte', 'ernährungsart', 3);
INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (2, 'vegetarisch', 'Ohne Fleisch Produkte', 'ernährungsart', 2);
INSERT INTO ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR, BEZEICHNUNG, BESCHREIBUNG, TYP, PRIORITAET) VALUES (3, 'fleisch essend', 'Alle produkte', 'ernährungsart', 1);
-- frutarisch
-- nur fisch und kein fleich

INSERT INTO ZUTAT_ERNAEHRUNGSKATEGORIE (ZUTATNR, ERNAEHRUNGSKATNR) VALUES (1, 1);

