DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;

CREATE TABLE ADRESSE (
    ADRESSENR       INTEGER NOT NULL,
    STRASSE         VARCHAR(50),
    HAURSNR         VARCHAR(10),
    POSTLEITZAHL    VARCHAR(5),
    ORT             VARCHAR(50),
    STADT           VARCHAR(50),
    LAND            VARCHAR(50),
    PRIMARY KEY (ADRESSENR)
);

CREATE TABLE LOGIN (
    USERNAME        VARCHAR(50),
    PASSHASH        VARCHAR(100),
    SECURITYANSWER  VARCHAR(100),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    ADRESSNR        INTEGER,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	DATE,
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    ABO             BOOLEAN,
    USERNAME        VARCHAR(50),
    PRIMARY KEY (KUNDENNR),
    FOREIGN KEY (ADRESSNR) REFERENCES ADRESSE (ADRESSENR),
    FOREIGN KEY (USERNAME) REFERENCES LOGIN (USERNAME)
);

CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    PRIMARY KEY (BESTELLNR),
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR)
);

CREATE TABLE NAHRUNGSBOX (
    BOXNR           INTEGER NOT NULL,
    BEZEICHNUNG     VARCHAR(50),
    BESCHREIBUNG    VARCHAR(500),
    PRIMARY KEY (BOXNR)
);

CREATE TABLE BESTELLUNG_BOX (
    BESTELLNR       INTEGER NOT NULL,
    BOXNR           INTEGER NOT NULL,
    MENGE           INTEGER,
    PRIMARY KEY (BESTELLNR,BOXNR),
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR),
    FOREIGN KEY (BOXNR) REFERENCES NAHRUNGSBOX (BOXNR)
);

CREATE TABLE REZEPT (
    REZEPTNR        INTEGER NOT NULL,
    NAME            VARCHAR(50),
    BESCHREIBUNG    VARCHAR(50),
    VORGEHEN        VARCHAR(2000),
    PRIMARY KEY (REZEPTNR)
);

CREATE TABLE NAHRUNGSBOX_REZEPT (
    BOXNR           INTEGER NOT NULL,
    REZEPTNR        INTEGER NOT NULL,
    MENGE_REZEPTE   INTEGER,
    PRIMARY KEY (BOXNR,REZEPTNR),
    FOREIGN KEY (BOXNR) REFERENCES NAHRUNGSBOX (BOXNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR)
);

CREATE TABLE LIEFERANT (
    LIEFNR      INTEGER NOT NULL,
    ADRESSNR    INTEGER,
    NAME        VARCHAR(50),
    PRIMARY KEY (LIEFNR),
    FOREIGN KEY (ADRESSNR) REFERENCES ADRESSE (ADRESSENR)
);

CREATE TABLE ZUTAT (
    ZUTATNR         INTEGER NOT NULL,
    LIEFNR          INTEGER,
    BEZEICHNUNG     VARCHAR(50),
    BESCHREIBUNG    VARCHAR(100),
    GEWICHT         DECIMAL(10,2),
    EINHEIT         VARCHAR(25),
    BESTAND         INTEGER,
    NETTOPREIS      DECIMAL(10,2),
    CO2             DECIMAL(10,2),
    KOHLENHYDRATE   DECIMAL(10,2),
    PROTEIN         DECIMAL(10,2),
    FETT            DECIMAL(10,2),
    KALORIEN        INTEGER,
    PRIMARY KEY (ZUTATNR),
    FOREIGN KEY (LIEFNR) REFERENCES LIEFERANT (LIEFNR)
);

CREATE TABLE REZEPT_ZUTAT (
    REZEPTNR        INTEGER NOT NULL,
    ZUTATNR         INTEGER NOT NULL,
    GEWICHT         DECIMAL(10,2),
    EINHEIT         VARCHAR(25),
    MENGE           INTEGER,
    PRIMARY KEY (REZEPTNR,ZUTATNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPT (REZEPTNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR)
);

CREATE TABLE ALERGEN (
    ALERGENNR       INTEGER NOT NULL,
    BEZEICHNUNG     VARCHAR(50),
    BESCHREIBUNG    VARCHAR(100),
    PRIMARY KEY (ALERGENNR)
);

CREATE TABLE ZUTAT_ALERGEN (
    ZUTATNR         INTEGER NOT NULL,
    ALERGENNR       INTEGER NOT NULL,
    PRIMARY KEY (ZUTATNR,ALERGENNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR),
    FOREIGN KEY (ALERGENNR) REFERENCES ALERGEN (ALERGENNR)
);

CREATE TABLE ERNAEHRUNGSKATEGORIE (
    ERNAEHRUNGSKATNR    INTEGER NOT NULL,
    BEZEICHNUNG         VARCHAR(50),
    BESCHREIBUNG        VARCHAR(100),
    TYP                 VARCHAR(25),
    PRIORITAET          INTEGER,
    PRIMARY KEY (ERNAEHRUNGSKATNR),
    UNIQUE (TYP,PRIORITAET)

    -- TODO:
);

CREATE TABLE ZUTAT_ERNAEHRUNGSKATEGORIE (
    ZUTATNR             INTEGER NOT NULL,
    ERNAEHRUNGSKATNR    INTEGER NOT NULL,
    PRIMARY KEY (ZUTATNR,ERNAEHRUNGSKATNR),
    FOREIGN KEY (ZUTATNR) REFERENCES ZUTAT (ZUTATNR),
    FOREIGN KEY (ERNAEHRUNGSKATNR) REFERENCES ERNAEHRUNGSKATEGORIE (ERNAEHRUNGSKATNR)
);